### ISSUE TITLE
Permission denied when ReadWriteMany volume is mounted by a new pod

### ISSUE THREAD

**Issue by Madhan-SWE** [kubernetes-sigs/ibm-powervs-block-csi-driver#174]
/kind bug

**What happened?**
Created and Mounted ReadWriteMany accesscode volume to pod app.
Created app2 pod with same volume.
When the app2 goes to running state. 
Permission denied when listing the files in the volume mounted directory.

**What you expected to happen?**
When access mode ReadWriteMany is set, all pods should be able to read and write to the volume mounted directory.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by Madhan-SWE** [comment]
**How to reproduce it (as minimally and precisely as possible)?**
Created storage class, PVC and pod with below yaml.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: powervs-sc3
provisioner: powervs.csi.ibm.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: tier3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powervs-claim3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: powervs-sc3
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: quay.io/centos/centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: powervs-claim3
```

Able to list files in data directory:
```
[root@rdr-madhan-f527-syd04-bastion-0 specs]# kubectl exec -it app --stdin  /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@app /]# ls data
[root@app /]# 
```

Created the second pod using the same volume.
```
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: app2
    image: quay.io/centos/centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: powervs-claim3
```

**Permission denied to list the files in app.**
```
[root@rdr-madhan-f527-syd04-bastion-0 specs]# kubectl exec -it app --stdin  /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@app /]# ls data
ls: cannot open directory 'data': Permission denied
```

Meanwhile able to list volume from app2.
```
[root@rdr-madhan-f527-syd04-bastion-0 specs]# kubectl exec -it app2 --stdin  /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@app2 /]# ls data
[root@app2 /]#
```
